name: Deploy to Vercel # Nama workflow

on:
  push:
    branches:
      - main # Workflow berjalan setiap ada push ke branch "main"

jobs:
  deploy:
    runs-on: ubuntu-latest # Workflow dijalankan di lingkungan Ubuntu

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        # Mengambil kode terbaru dari repository

      - name: Install Vercel CLI
        run: npm install -g vercel
        # Menginstal Vercel CLI untuk deployment

      - name: Pull Vercel Environment
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        # Mengambil konfigurasi environment dari Vercel

      - name: Deploy to Vercel
        id: deploy
        run: |
          # Melakukan deployment ke Vercel dan menyimpan URL hasil deploy
          DEPLOY_URL=$(vercel --prod --token=${{ secrets.VERCEL_TOKEN }})
          echo "Deployment URL: $DEPLOY_URL"
          echo "DEPLOY_URL=$DEPLOY_URL" >> $GITHUB_ENV

      - name: Commit Deployment Status
        run: |
          # Konfigurasi Git
          git config --global user.name "[BOT] GitHub Actions"
          git config --global user.email "actions@github.com"

          # Buat branch baru untuk PR
          git checkout -b deploy-update
          git pull origin main --rebase

          # Commit perubahan (commit kosong untuk update status)
          git commit --allow-empty -m "🚀 Deployed successfully to Vercel: $DEPLOY_URL"

          # Push perubahan ke branch baru
          git push origin deploy-update

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Membuat PR otomatis dari "deploy-update" ke "main"
          gh pr create \
            --base main \
            --head deploy-update \
            --title "🚀 Deployment Update" \
            --body "This PR confirms that the deployment to Vercel was successful. View the deployed app here: $DEPLOY_URL" \
            --label "deployment"
