name: Deploy to Vercel # Nama workflow

on:
  push:
    branches:
      - main # Workflow berjalan setiap ada push ke branch "main"

jobs:
  deploy:
    runs-on: ubuntu-latest # Workflow dijalankan di lingkungan Ubuntu

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        # Mengambil kode terbaru dari repository

      - name: Install Vercel CLI
        run: npm install -g vercel
        # Menginstal Vercel CLI untuk deployment

      - name: Pull Vercel Environment
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        # Mengambil konfigurasi environment dari Vercel

      - name: Deploy to Vercel
        id: deploy
        run: |
          # Melakukan deployment ke Vercel dan menyimpan URL hasil deploy
          DEPLOY_URL=$(vercel --prod --token=${{ secrets.VERCEL_TOKEN }})
          echo "Deployment URL: $DEPLOY_URL"
          echo "DEPLOY_URL=$DEPLOY_URL" >> $GITHUB_ENV

      - name: Create Deployment Branch
        run: |
          # Konfigurasi Git
          git config --global user.name "[BOT] GitHub Actions"
          git config --global user.email "actions@github.com"

          # Pastikan branch main terbaru
          git checkout main
          git pull origin main --rebase

          # Hapus branch `deploy-update` jika ada (mencegah error push)
          git branch -D deploy-update || true
          git push origin --delete deploy-update || true

          # Buat branch `deploy-update` dari `main`
          git checkout -b deploy-update

          # Commit perubahan (commit kosong untuk update status)
          git commit --allow-empty -m "🚀 Deployed successfully to Vercel: $DEPLOY_URL"

          # Push perubahan ke branch `deploy-update`
          git push origin deploy-update

      - name: Check Existing Pull Requests
        id: check_pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Cek apakah sudah ada PR dari deploy-update ke main
          PR_COUNT=$(gh pr list --base main --head deploy-update --json number --jq '. | length')
          echo "EXISTING_PR_COUNT=$PR_COUNT" >> $GITHUB_ENV

      - name: Create Pull Request
        if: env.EXISTING_PR_COUNT == '0'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Membuat PR otomatis dari "deploy-update" ke "main"
          gh pr create \
            --base main \
            --head deploy-update \
            --title "🚀 Deployment Update" \
            --body "This PR confirms that the deployment to Vercel was successful. View the deployed app here: $DEPLOY_URL" \
            --label "deployment"
